[Q_value,wyb_akcja]=f_best_action_in_state(Q_2d, stan, nr_stanu_doc);
wyb_akcja2=randi([wyb_akcja-RD, wyb_akcja+RD], [1, 1]);
if wyb_akcja2>wyb_akcja_under-RD &&...
        wyb_akcja2>wyb_akcja_above-RD &&...
        wyb_akcja2<wyb_akcja_under+RD &&...
        wyb_akcja2<wyb_akcja_above+RD &&...
        wyb_akcja2~=nr_akcji_doc %&&...
    %(wyb_akcja > nr_akcji_doc && stan > nr_stanu_doc) &&...
    %(wyb_akcja < nr_akcji_doc && stan < nr_stanu_doc)
    ponowne_losowanie=0;
    wyb_akcja=wyb_akcja2;
else
    ponowne_losowanie=ponowne_losowanie+1;
end